"""Constants for Matter Binding Studio."""

DOMAIN = "matter_binding_studio"

PANEL_NAME = "matter-binding-studio-panel"
PANEL_TITLE = "Matter Binding Studio"
PANEL_ICON = "mdi:transit-connection-variant"

WS_TYPE_GET_SNAPSHOT = f"{DOMAIN}/get_snapshot"

CLUSTER_BINDING = 0x001E
CLUSTER_COLOR_CONTROL = 0x0300
CLUSTER_DESCRIPTOR = 0x001D
CLUSTER_GROUPS = 0x0004
CLUSTER_GROUP_KEY_MANAGEMENT = 0x003F
CLUSTER_LEVEL_CONTROL = 0x0008
CLUSTER_ON_OFF = 0x0006

ATTR_BINDING = 0
ATTR_GROUP_TABLE = 1
ATTR_GROUP_KEY_MAP = 0
ATTR_MAX_GROUP_KEYS_PER_FABRIC = 3
ATTR_MAX_GROUPS_PER_FABRIC = 2
ATTR_CLIENT_LIST = 2
ATTR_SERVER_LIST = 1
