export type Language = "zh-Hant" | "en";

const zhHant = {
  appName: "Matter Binding Studio",
  subtitle: "以 Home Assistant 名稱檢視原生 Matter Binding",
  directBinding: "原生直接 Binding",
  refresh: "重新整理",
  refreshing: "更新中…",
  scope:
    "選擇一個目標時建立原生直接 Binding；選擇多個目標時，Studio 會自動建立並驗證原生群組廣播。",
  loading: "正在讀取 Matter Fabric…",
  readFailed: "目前無法讀取 Matter Fabric，請稍後重新整理。",
  notConnected: "此預覽尚未連接到 Home Assistant。",
  controlRelationships: "控制關係",
  relationshipDescription: "以 Home Assistant 裝置名稱呈現的既有原生 Matter Binding。",
  noRelationships: "沒有讀到可呈現的控制關係。",
  direct: "直接連線",
  nativeGroup: "原生群組",
  members: "個目標",
  controlSets: "原生控制組",
  controlSetsDescription:
    "自動建立的控制組僅用來說明哪些目標會一起被控制；不需要手動管理 Group ID 或 Group Key。",
  noControlSets: "沒有讀到可呈現的原生控制組。",
  activeRelationships: "條使用中的關係",
  controlSetPending: "此控制組尚在建立，尚未視為可用。",
  controlSetRepairNeeded: "此控制組需要修復；請先檢查實體裝置的群組設定。",
  capacity: "群組與 Group Key 容量",
  capacityDescription:
    "裝置回報且已快取的限制。建立群組廣播前會先做容量預檢。",
  groups: "群組",
  groupKeys: "Group Key",
  unavailable: "尚未取得",
  onOff: "開關",
  brightness: "亮度",
  colorTemperature: "色溫",
  addRelationship: "新增控制關係",
  addRelationshipDescription:
    "先選來源、目標與能力，再檢視實際會寫入的原生 Matter 交易。",
  source: "控制來源",
  target: "控制目標",
  targets: "控制目標（可多選）",
  chooseSource: "選擇可 Binding 的控制來源",
  chooseTarget: "選擇輸出目標",
  noTargets: "目前沒有符合篩選條件的輸出目標。",
  sameAreaOnly: "僅顯示與來源相同區域的目標",
  capabilities: "要控制的能力",
  noSharedCapabilities: "所選 endpoint 沒有可共同 Binding 的能力。",
  coverageReady: "完整支援",
  coveragePartial: "部分支援",
  notSupportedBy: "不支援的目標",
  reviewPlan: "檢視寫入計畫",
  reviewTitle: "確認原生 Matter 寫入",
  aclWillAdd: "寫入前會在目標裝置補上必要的操作 ACL。",
  aclAlreadyGranted: "目標裝置已經具備必要的操作 ACL。",
  groupAclReview: "Studio 會為每個支援該能力的目標補上必要的群組操作 ACL。",
  replacesDirect: "這會在群組佈建完成後，將選取目標的相同直接 Binding 改為群組廣播。",
  confirmWrite: "我已確認此操作會變更真實 Matter 裝置的 ACL 與 Binding。",
  applyBinding: "寫入並讀回驗證",
  working: "處理中…",
};

const en: typeof zhHant = {
  appName: "Matter Binding Studio",
  subtitle: "Inspect native Matter bindings with Home Assistant names",
  directBinding: "Native direct binding",
  refresh: "Refresh",
  refreshing: "Refreshing…",
  scope:
    "One target creates a native direct binding. Multiple targets create and verify an automatically managed native groupcast.",
  loading: "Reading the Matter fabric…",
  readFailed: "Matter Fabric could not be read. Please try refreshing again.",
  notConnected: "This preview is not connected to Home Assistant.",
  controlRelationships: "Control relationships",
  relationshipDescription:
    "Existing native Matter bindings, shown with Home Assistant device names.",
  noRelationships: "No readable control relationships were found.",
  direct: "Direct",
  nativeGroup: "Native group",
  members: "targets",
  controlSets: "Native control sets",
  controlSetsDescription:
    "Automatic control sets explain which targets act together. Group IDs and Group Keys are never a manual management task.",
  noControlSets: "No readable native control sets were found.",
  activeRelationships: "active relationships",
  controlSetPending: "This control set is still being created and is not considered ready.",
  controlSetRepairNeeded: "This control set needs repair. Check its physical Matter group configuration first.",
  capacity: "Group and Group Key capacity",
  capacityDescription:
    "Cached device-reported limits. Groupcast creation preflights this capacity before making changes.",
  groups: "Groups",
  groupKeys: "Group Keys",
  unavailable: "Unavailable",
  onOff: "On / Off",
  brightness: "Brightness",
  colorTemperature: "Color temperature",
  addRelationship: "Add control relationship",
  addRelationshipDescription:
    "Choose a source, target, and capability, then review the native Matter transaction before any device is changed.",
  source: "Control source",
  target: "Control target",
  targets: "Control targets (multiple allowed)",
  chooseSource: "Choose a bindable control source",
  chooseTarget: "Choose an output target",
  noTargets: "No output targets match the current filter.",
  sameAreaOnly: "Only show targets in the source area",
  capabilities: "Capabilities to control",
  noSharedCapabilities: "The selected endpoints have no compatible binding capability.",
  coverageReady: "ready",
  coveragePartial: "partial",
  notSupportedBy: "Not supported by",
  reviewPlan: "Review write plan",
  reviewTitle: "Confirm native Matter write",
  aclWillAdd: "The required operate ACL will be added to the target before binding.",
  aclAlreadyGranted: "The target already grants the required operate ACL.",
  groupAclReview: "Studio will add the required group operate ACL to every target that supports each selected capability.",
  replacesDirect: "After group provisioning succeeds, matching direct bindings for the selected targets will be converted to groupcast.",
  confirmWrite: "I understand this changes the real Matter device ACL and Binding.",
  applyBinding: "Write and verify",
  working: "Working…",
};

export const copy = { "zh-Hant": zhHant, en };
export type Copy = typeof zhHant;
