export type Language = "zh-Hant" | "en";

const zhHant = {
  appName: "Matter Binding Studio",
  subtitle: "以 Home Assistant 名稱檢視原生 Matter Binding",
  directBinding: "原生直接 Binding",
  refresh: "重新整理",
  refreshing: "更新中…",
  scope:
    "可建立並驗證單一目標的原生 unicast Binding。多目標的原生 groupcast 會在另一個受控交易中加入。",
  loading: "正在讀取 Matter Fabric…",
  readFailed: "目前無法讀取 Matter Fabric，請稍後重新整理。",
  notConnected: "此預覽尚未連接到 Home Assistant。",
  controlRelationships: "控制關係",
  relationshipDescription: "以 Home Assistant 裝置名稱呈現的既有原生 Matter Binding。",
  noRelationships: "沒有讀到可呈現的控制關係。",
  direct: "直接連線",
  nativeGroup: "原生群組",
  members: "個目標",
  controlSets: "原生控制組",
  controlSetsDescription:
    "由裝置快取的 Groups table 推得。這個階段不會宣告或變更任何群組的擁有權。",
  noControlSets: "沒有讀到可呈現的原生控制組。",
  activeRelationships: "條使用中的關係",
  capacity: "群組與 Group Key 容量",
  capacityDescription:
    "裝置回報且已快取的限制。未來的群組廣播建立前會先做容量預檢。",
  groups: "群組",
  groupKeys: "Group Key",
  unavailable: "尚未取得",
  onOff: "開關",
  brightness: "亮度",
  colorTemperature: "色溫",
  addRelationship: "新增控制關係",
  addRelationshipDescription:
    "先選來源、目標與能力，再檢視實際會寫入的原生 Matter 交易。",
  source: "控制來源",
  target: "控制目標",
  chooseSource: "選擇可 Binding 的控制來源",
  chooseTarget: "選擇輸出目標",
  capabilities: "要控制的能力",
  noSharedCapabilities: "這兩個 endpoint 沒有可共同 Binding 的能力。",
  reviewPlan: "檢視寫入計畫",
  reviewTitle: "確認原生 Matter 寫入",
  aclWillAdd: "寫入前會在目標裝置補上必要的操作 ACL。",
  aclAlreadyGranted: "目標裝置已經具備必要的操作 ACL。",
  confirmWrite: "我已確認此操作會變更真實 Matter 裝置的 ACL 與 Binding。",
  applyBinding: "寫入並讀回驗證",
  working: "處理中…",
};

const en: typeof zhHant = {
  appName: "Matter Binding Studio",
  subtitle: "Inspect native Matter bindings with Home Assistant names",
  directBinding: "Native direct binding",
  refresh: "Refresh",
  refreshing: "Refreshing…",
  scope:
    "Create and verify single-target native unicast bindings. Native groupcast for multiple targets will be a separate guarded transaction.",
  loading: "Reading the Matter fabric…",
  readFailed: "Matter Fabric could not be read. Please try refreshing again.",
  notConnected: "This preview is not connected to Home Assistant.",
  controlRelationships: "Control relationships",
  relationshipDescription:
    "Existing native Matter bindings, shown with Home Assistant device names.",
  noRelationships: "No readable control relationships were found.",
  direct: "Direct",
  nativeGroup: "Native group",
  members: "targets",
  controlSets: "Native control sets",
  controlSetsDescription:
    "Derived from cached device Groups tables. Studio does not claim or change ownership of any group in this stage.",
  noControlSets: "No readable native control sets were found.",
  activeRelationships: "active relationships",
  capacity: "Group and Group Key capacity",
  capacityDescription:
    "Cached device-reported limits. A future groupcast action will preflight this capacity before making changes.",
  groups: "Groups",
  groupKeys: "Group Keys",
  unavailable: "Unavailable",
  onOff: "On / Off",
  brightness: "Brightness",
  colorTemperature: "Color temperature",
  addRelationship: "Add control relationship",
  addRelationshipDescription:
    "Choose a source, target, and capability, then review the native Matter transaction before any device is changed.",
  source: "Control source",
  target: "Control target",
  chooseSource: "Choose a bindable control source",
  chooseTarget: "Choose an output target",
  capabilities: "Capabilities to control",
  noSharedCapabilities: "These endpoints have no compatible binding capability.",
  reviewPlan: "Review write plan",
  reviewTitle: "Confirm native Matter write",
  aclWillAdd: "The required operate ACL will be added to the target before binding.",
  aclAlreadyGranted: "The target already grants the required operate ACL.",
  confirmWrite: "I understand this changes the real Matter device ACL and Binding.",
  applyBinding: "Write and verify",
  working: "Working…",
};

export const copy = { "zh-Hant": zhHant, en };
export type Copy = typeof zhHant;
